title: Those Who Rule wiki demo
description: Portfolio display of personal project wiki.gg page for indie strategy RPG Those Who Rule.
theme: just-the-docs

url: https://williamplacroix.github.io/TWR-wiki-demo/

aux_links:
  View the wiki: https://thosewhorule.wiki.gg/
